// SPDX-License-Identifier: Apache-2.0
'use strict';
const BASE='http://127.0.0.1:54123', TOKEN=__BRIDGE_TOKEN__;
const instance=Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
let runId=null,seen=0,polling=false,sending=false,toolBusy=false,serviceReady=false,configuration=null,settingsBusy=false,checkingConnection=false;
const modelCache={}, $=id=>document.getElementById(id);
let activeTab='chat',planKey='',contextKey='',latestNetwork=null,networkDirty=false,networkFrame=null,networkPaintId=0,scrollFrame=null,followMessages=true,pollTimer=null,lastPollFailed=false;
let expanded=false;
const pendingToolRows=new Map(), MAX_TOOL_ROWS=120;
function setText(id,text){if($(id).textContent!==text)$(id).textContent=text;}

/* XMLHttpRequest works in Packet Tracer custom-scheme webviews. */
function request(path,data,timeout=10000){return new Promise((resolve,reject)=>{
 const x=new XMLHttpRequest();x.open(data===undefined?'GET':'POST',BASE+path,true);x.timeout=timeout;
 x.setRequestHeader('Authorization','Bearer '+TOKEN);
 if(data!==undefined)x.setRequestHeader('Content-Type','application/json');
 x.onload=()=>{let result;try{result=JSON.parse(x.responseText);}catch(e){reject(new Error('The local service returned an invalid response.'));return;}
  if(x.status<200||x.status>=300){const error=new Error(result.error||'Service HTTP '+x.status);error.status=x.status;reject(error);}else resolve(result);};
 x.onerror=()=>reject(new Error('Local HTTP request was blocked or the service is stopped. Reload the updated extension and use the AI launcher.'));
 x.ontimeout=()=>reject(new Error('Local service request timed out. Check the service, then retry.'));
 x.send(data===undefined?null:JSON.stringify(data));
});}
function showTab(name){activeTab=name;document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===name));document.querySelectorAll('.tab-content').forEach(t=>t.classList.toggle('active',t.id===name+'-tab'));if(name==='settings'&&!configuration)loadSettings();if(name==='network')scheduleNetwork();}
function scroll(){if(scrollFrame!==null)return;scrollFrame=requestAnimationFrame(()=>{scrollFrame=null;if(activeTab==='chat'&&followMessages)$('messages').scrollTop=$('messages').scrollHeight;});}
function bubble(label,text,error=false){if(label==='You')followMessages=true;const b=document.createElement('div');b.className='bubble '+(label==='You'?'user ':'')+(error?'error':'');const l=document.createElement('div');l.className='label';l.textContent=label;b.append(l,document.createTextNode(text));$('messages').appendChild(b);scroll();}
function formatToolRow(d){if(!d.open||d._rendered)return;d._rendered=true;const p=document.createElement('pre');let truncated=false;let text=JSON.stringify(d._event.result||d._event.args,(key,value)=>{if(typeof value==='string'&&value.length>8000){truncated=true;return value.slice(0,8000)+'…';}if(Array.isArray(value)&&value.length>50){truncated=true;return value.slice(0,50);}return value;},2)||'';if(text.length>32000){truncated=true;text=text.slice(0,32000);}p.textContent=text+(truncated?'\n[Display preview truncated; the service retains the full tool result.]':'');d.appendChild(p);}
function toolEvent(event){let queue=pendingToolRows.get(event.name)||[],d=event.kind==='tool_result'?queue.shift():null;
 if(!d){d=document.createElement('details');d.className='tool-row';d.appendChild(document.createElement('summary'));d.addEventListener('toggle',()=>formatToolRow(d));$('messages').appendChild(d);}
 if(event.kind==='tool_start'){queue.push(d);pendingToolRows.set(event.name,queue);}else if(!queue.length)pendingToolRows.delete(event.name);
 d._event=event;d._rendered=false;const previous=d.querySelector('pre');if(previous)previous.remove();
 const result=event.kind==='tool_result',ok=result&&event.result&&event.result.ok;d.classList.toggle('tool-success',!!ok);d.classList.toggle('tool-error',result&&!ok);
 d.firstChild.textContent=(result?(ok?'✓':'!'):'↗')+' '+event.name.replace(/_/g,' ')+(result?'':' · running');formatToolRow(d);
 const rows=$('messages').querySelectorAll('.tool-row');let remaining=rows.length;for(const row of rows){if(remaining<=MAX_TOOL_ROWS)break;if(row._event.kind==='tool_result'&&!row.open){row.remove();remaining--;}}
 if(rows.length>MAX_TOOL_ROWS&&!$('tool-log-note')){const note=document.createElement('div');note.id='tool-log-note';note.className='small-note';note.textContent='Showing recent tool activity. Full results remain in the service for this run.';$('messages').insertBefore(note,$('messages').firstChild);}scroll();}
function renderPlan(steps){const key=JSON.stringify(steps||[]);if(key===planKey)return;planKey=key;$('plan').classList.toggle('hidden',!steps||!steps.length);$('plan-steps').replaceChildren();for(const step of steps||[]){const li=document.createElement('li');li.className=step.status;const icon=document.createElement('span');icon.textContent={pending:'○',in_progress:'◉',done:'✓',failed:'!'}[step.status]||'○';li.append(icon,document.createTextNode(step.title));$('plan-steps').appendChild(li);}}
function setDisabled(id,value){const disabled=!!value;if($(id).disabled!==disabled)$(id).disabled=disabled;}
function updateButtons(){setDisabled('send',sending||!!runId||!serviceReady||settingsBusy);setDisabled('stop',!runId);setDisabled('newchat',!!runId||sending);setDisabled('mode',!!runId||sending);setDisabled('context-device',!!runId||sending);setDisabled('snapshot',!!runId||sending||!serviceReady);setDisabled('save-settings',settingsBusy||!!runId);setDisabled('load-models',settingsBusy||!!runId);setDisabled('test-service',settingsBusy||checkingConnection);setDisabled('provider',settingsBusy);setDisabled('api-key',settingsBusy);setDisabled('model',settingsBusy);setDisabled('model-list',settingsBusy);}
function populateContext(devices){const key=JSON.stringify(devices.map(d=>[d.name,d.model]));if(key===contextKey)return;contextKey=key;const prior=$('context-device').value,fragment=document.createDocumentFragment();fragment.appendChild(new Option('Whole network',''));for(const d of devices){fragment.appendChild(new Option('@'+d.name+' · '+d.model,d.name));}$('context-device').replaceChildren(fragment);if(devices.some(d=>d.name===prior))$('context-device').value=prior;}
function renderNetwork(snapshot){const devices=snapshot.devices||(snapshot.device?[snapshot.device]:[]);if(!devices.length&&snapshot.device_count!==0)return;
 latestNetwork=snapshot;networkDirty=true;if(snapshot.devices)populateContext(devices);scheduleNetwork();}
function scheduleNetwork(){if(activeTab!=='network'||!networkDirty||networkFrame!==null)return;networkFrame=requestAnimationFrame(()=>{networkFrame=null;if(activeTab==='network'&&networkDirty){networkDirty=false;paintNetwork(latestNetwork);}});}
function paintNetwork(snapshot){const devices=snapshot.devices||(snapshot.device?[snapshot.device]:[]),paintId=++networkPaintId;let cursor=0;$('network-cards').replaceChildren();setText('network-count',devices.length+' devices'+(snapshot.link_count!==undefined?' · '+snapshot.link_count+' links':'')+' · live snapshot');
 if(!devices.length){const e=document.createElement('div');e.className='empty';e.textContent='This lab has no devices yet. Ask Agent to build a network.';$('network-cards').appendChild(e);return;}
 function appendNext(){if(paintId!==networkPaintId||snapshot!==latestNetwork)return;if(activeTab!=='network'){networkDirty=true;return;}const fragment=document.createDocumentFragment(),end=Math.min(cursor+10,devices.length);
 for(;cursor<end;cursor++){const d=devices[cursor],card=document.createElement('div');card.className='device-card';const title=document.createElement('div');title.className='device-title';const name=document.createElement('strong');name.textContent=d.name;const model=document.createElement('span');model.textContent=d.model;title.append(name,model);card.appendChild(title);
  for(const port of d.ports||[]){const p=document.createElement('div');p.className='device-port '+(port.up===true?'up':port.up===false?'down':'');p.textContent=port.name+' · '+(port.up===true?'up':port.up===false?'down':'unknown')+(port.address?' · '+port.address:'')+(port.peer_device?' → '+port.peer_device+' / '+port.peer_port:'');card.appendChild(p);}
  const use=document.createElement('button');use.textContent='Use as context';use.onclick=()=>{if(!Array.from($('context-device').options).some(o=>o.value===d.name))$('context-device').appendChild(new Option('@'+d.name,d.name));$('context-device').value=d.name;showTab('chat');$('prompt').focus();};card.appendChild(use);fragment.appendChild(card);}$('network-cards').appendChild(fragment);if(cursor<devices.length)requestAnimationFrame(appendNext);}
 appendNext();
}
async function send(){if(sending||runId)return;const text=$('prompt').value.trim();if(!text)return;sending=true;updateButtons();bubble('You',text);$('prompt').value='';$('intro').classList.add('hidden');try{const r=await request('/chat',{message:text,mode:$('mode').value,context_device:$('context-device').value});runId=r.id;seen=0;renderPlan([]);$('taskstate').textContent='Reading context…';}catch(e){bubble('Service',e.message,true);}finally{sending=false;updateButtons();tick();}}
window.agentResult=async(id,result)=>{try{await request('/bridge/result',{id,result,instance});}catch(e){bubble('Connection','Could not return tool results: '+e.message,true);}finally{toolBusy=false;}};
function configMessage(text,error=false){$('settings-status').textContent=text;$('settings-status').classList.toggle('error',error);}
function selectProvider(){if(!configuration)return;const provider=$('provider').value,meta=configuration.providers[provider];$('api-key').value='';$('api-key').type='password';$('show-key').textContent='Show';$('key-state').textContent=meta.environment_key?'Environment key':meta.key_configured?'Key saved':'No key saved';$('model').value=configuration.models[provider]||'';renderModels(provider);}
function renderModels(provider){const list=modelCache[provider]||[];$('model-list').replaceChildren(new Option(list.length?'Choose a model…':'Fetch models to see the available choices',''));for(const m of list){const option=new Option(m.name+(m.name!==m.id?' · '+m.id:'')+(m.tools===false?' · chat only':''),m.id);$('model-list').appendChild(option);}if(list.some(m=>m.id===$('model').value))$('model-list').value=$('model').value;}
async function loadSettings(){try{configuration=await request('/config');$('provider').value=configuration.provider;$('max-steps').value=configuration.max_steps;selectProvider();return true;}catch(e){configMessage(e.message,true);return false;}}
async function saveSettings(){const provider=$('provider').value;configuration=await request('/config',{provider,model:$('model').value.trim(),api_key:$('api-key').value,max_steps:Number($('max-steps').value)});$('api-key').value='';$('key-state').textContent=configuration.providers[provider].environment_key?'Environment key':configuration.providers[provider].key_configured?'Key saved':'No key saved';return configuration;}
async function fetchModels(){const provider=$('provider').value,r=await request('/models',{provider,api_key:$('api-key').value},45000);modelCache[provider]=r.models;
 if(!r.models.length)throw new Error('The provider returned no chat models for this key.');
 if(!r.models.some(m=>m.id===$('model').value.trim())){$('model').value=(r.models.find(m=>m.id==='gemini-3.8-flash')||r.models.find(m=>m.tools!==false)||r.models[0]).id;}
 renderModels(provider);$('model-help').textContent=r.models.length+' models available. Selected: '+$('model').value+'. Save & use to activate it.';return r;}
async function checkConnection(){if(checkingConnection||settingsBusy)return;checkingConnection=true;settingsBusy=true;updateButtons();$('test-service').textContent='Checking…';const result=$('connection-result');result.textContent='Checking local service…';result.classList.remove('error');
 try{const status=await request('/status');serviceReady=true;result.textContent='Local service reachable. '+(status.connected?'Packet Tracer connected. ':'Open the extension in Packet Tracer to connect the simulator. ');
  result.textContent+='Checking '+$('provider').selectedOptions[0].textContent+'…';const r=await fetchModels();result.textContent='Local service reachable. '+(status.connected?'Packet Tracer connected. ':'Simulator disconnected. ')+$('provider').selectedOptions[0].textContent+' key accepted · '+r.models.length+' models available. Model inference also depends on account quota.';
 }catch(e){result.textContent=e.message;result.classList.add('error');}finally{checkingConnection=false;settingsBusy=false;$('test-service').textContent='Check connection';updateButtons();}}
async function tick(){if(polling)return;clearTimeout(pollTimer);polling=true;try{
 const hasIPC=typeof window.$se==='function';
 let status;if(hasIPC){const r=await request('/bridge/poll',{instance,busy:toolBusy,include_status:true});status=r.status;if(r.job){toolBusy=true;try{$se('dispatchAgentJob',JSON.stringify(r.job));}catch(e){await window.agentResult(r.job.id,{ok:false,error:e.message});}}}
 if(!status)status=await request('/status');serviceReady=true;lastPollFailed=false;
 if(status.active_run&&runId!==status.active_run){runId=status.active_run;seen=0;pendingToolRows.clear();$('intro').classList.add('hidden');}
 $('dot').classList.toggle('ready',status.connected);setText('status',status.connected?'Connected to Packet Tracer':hasIPC?'Service connected · waiting for simulator':'Service connected · browser preview');
 setText('model-chip',(status.provider||'openai')+' / '+(status.model||'Choose model'));
 setText('connection-details','Local service v'+(status.service_version||'0.1')+' is reachable. '+(status.connected?'Simulator bridge connected.':'Simulator bridge is not connected. Open the Agent extension in Packet Tracer.'));
 const missing=!status.key_configured||!status.model;$('notice').classList.toggle('hidden',!missing);setText('notice',!status.key_configured?'Connect your provider in Settings to use the assistant. Network snapshots work without a key.':'Choose a model in Settings before sending a message.');
 if(!configuration)await loadSettings();
 if(runId){let r;try{r=await request('/runs/'+runId+'?after='+seen);}catch(error){if(error.status!==404)throw error;runId=null;seen=0;pendingToolRows.clear();renderPlan([]);setText('taskstate','Previous task history unavailable');bubble('Service','The service restarted or expired this task history. Refresh the network before continuing.');return;}const events=r.next_event===undefined?r.events.slice(seen):r.events;for(const event of events){if(event.kind==='assistant')bubble('Assistant',event.text);else if(event.kind==='plan')renderPlan(event.steps);else if(event.kind==='context')renderNetwork(event.snapshot);else if(event.kind==='tool_start'||event.kind==='tool_result'){toolEvent(event);if(event.kind==='tool_result'&&event.result&&event.result.ok&&(event.name==='inspect_topology'||event.name==='inspect_device'))renderNetwork(event.result);}}seen=r.next_event===undefined?r.events.length:r.next_event;
  if(r.plan)renderPlan(r.plan);if(r.status!=='running'&&!r.has_more){if(r.status!=='done')bubble('Assistant',r.answer,true);else if(!(r.has_assistant===undefined?r.events.some(e=>e.kind==='assistant'):r.has_assistant))bubble('Assistant',r.answer);setText('taskstate',r.status==='done'?'Task complete':r.status);runId=null;}else setText('taskstate',toolBusy?'Executing in simulator…':'Working · '+(r.model||'network snapshot'));}
 }catch(e){serviceReady=false;lastPollFailed=true;$('dot').classList.remove('ready');setText('status','Connection unavailable');setText('connection-details',e.message+' Service: '+BASE);$('notice').classList.remove('hidden');setText('notice',e.message);}
 finally{polling=false;updateButtons();pollTimer=setTimeout(tick,lastPollFailed?4000:runId||toolBusy?500:2000);}}

document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
$('messages').addEventListener('scroll',()=>{const m=$('messages');followMessages=m.scrollHeight-m.clientHeight-m.scrollTop<64;},{passive:true});
$('settings-shortcut').onclick=()=>showTab('settings');$('model-chip').onclick=()=>showTab('settings');
window.agentWindowState=value=>{expanded=!!value;setText('expand-chat',expanded?'Resize':'Expand');$('expand-chat').title=expanded?'Return the panel inside Packet Tracer':'Open a larger chat window';$('expand-chat').setAttribute('aria-pressed',String(expanded));};
$('expand-chat').onclick=()=>{if(typeof window.$se==='function')$se('expandAgent');else if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen().catch(()=>{});};
document.addEventListener('fullscreenchange',()=>{if(typeof window.$se!=='function')window.agentWindowState(!!document.fullscreenElement);});
$('send').onclick=send;$('prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(!$('send').disabled)send();}};
$('reconnect').onclick=tick;$('test-service').onclick=checkConnection;
$('snapshot').onclick=async()=>{if(sending||runId)return;sending=true;updateButtons();try{const r=await request('/diagnose',{});runId=r.id;seen=0;$('intro').classList.add('hidden');$('taskstate').textContent='Reading network…';}catch(e){bubble('Service',e.message,true);showTab('chat');}finally{sending=false;updateButtons();tick();}};
$('stop').onclick=async()=>{try{await request('/stop',{id:runId});$('taskstate').textContent='Stopping…';}catch(e){bubble('Service',e.message,true);}};
$('newchat').onclick=async()=>{try{await request('/reset',{});document.querySelectorAll('.bubble,details,#tool-log-note').forEach(e=>e.remove());pendingToolRows.clear();followMessages=true;$('intro').classList.remove('hidden');renderPlan([]);$('taskstate').textContent='New conversation';}catch(e){bubble('Service',e.message,true);}};
document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{$('prompt').value=b.dataset.example;$('mode').value=b.dataset.mode;$('prompt').focus();});
$('provider').onchange=()=>{selectProvider();configMessage('');$('connection-result').textContent='';$('model-help').textContent='Fetch models to check your key and load the provider’s available models.';};$('model-list').onchange=()=>{if($('model-list').value)$('model').value=$('model-list').value;};
$('show-key').onclick=()=>{$('api-key').type=$('api-key').type==='password'?'text':'password';$('show-key').textContent=$('api-key').type==='password'?'Show':'Hide';};
$('settings-form').onsubmit=async e=>{e.preventDefault();if(settingsBusy)return;settingsBusy=true;updateButtons();configMessage('Saving…');try{await saveSettings();configMessage('Saved. This provider and model will be used for your next task.');await tick();}catch(error){configMessage(error.message,true);}finally{settingsBusy=false;updateButtons();}};
$('load-models').onclick=async()=>{if(settingsBusy)return;settingsBusy=true;updateButtons();$('load-models').textContent='Loading…';configMessage('Checking key and loading models…');try{const r=await fetchModels();configMessage(r.models.length+' models loaded. Choose one, then Save & use.');}catch(e){configMessage(e.message,true);}finally{settingsBusy=false;$('load-models').textContent='Fetch models';updateButtons();}};
tick();updateButtons();
